version: '3'

services:

  nginx:
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
    environment:
      - BACKEND="https://141.158.63.251"
      - PROXY=1
    network_mode: host

  # certbot:
  #   image: certbot/certbot

  fail2ban:
    build: fail2ban/
    # image: crazymax/fail2ban
    restart: always
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/fail2ban.log:/var/log/fail2ban.log
      - ./fail2ban/jail.conf:/etc/fail2ban/jail.conf
      - ./fail2ban/jail.conf:/etc/fail2ban/jail.local
      - ./fail2ban/filter.d/:/etc/fail2ban/filter.d/
    environment:
      - TZ=America/New_York
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=DEBUG
      - F2B_DB_PURGE_AGE=1d
    cap_add:
      - NET_ADMIN
      - NET_RAW    
    network_mode: host
