version: '3'

services:

  nginx:
    image: owasp/modsecurity-crs:nginx-alpine
    restart: always
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./certbot/certs/:/certs/
    environment:
      - BACKEND="https://141.158.63.251"
      - PROXY=1
      - PROXY_SSL_CERT="/certs/fullchain.pem"
      - PROXY_SSL_CERT_KEY="/certs/privkey.pem"
    network_mode: host

  certbot:
    image: certbot/dns-digitalocean
    restart: on-failure
    command: certonly -v --dns-digitalocean --dns-digitalocean-credentials /root/certbot-creds.ini --agree-tos --email ${EMAIL} -n -d *.${DOMAIN} --deploy-hook="/certs/copy-certs.sh"
    volumes:
      - ./certbot/certs/:/certs/
      - ./certbot/entrypoint.sh:/entrypoint.sh
    env_file:
      - certbot/certbot.env
    entrypoint: /entrypoint.sh

      
  fail2ban:
    build: fail2ban/
    restart: always
    volumes:
      - ./logs/access.log:/var/log/nginx/access.log
      - ./logs/error.log:/var/log/nginx/error.log
      - ./logs/fail2ban.log:/var/log/fail2ban.log
      - ./fail2ban/jail.conf:/etc/fail2ban/jail.conf
      - ./fail2ban/jail.conf:/etc/fail2ban/jail.local
      - ./fail2ban/filter.d/:/etc/fail2ban/filter.d/
    environment:
      - TZ=America/New_York
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=DEBUG
      - F2B_DB_PURGE_AGE=1d
    cap_add:
      - NET_ADMIN
      - NET_RAW    
    network_mode: host
